dist: bionic
language: python
cache: pip

before_script:
  - pip install tox
  - if [ ${TOXENV} = py310 ]; then sudo apt-get update && sudo apt-get install ffmpeg; fi

script: tox

matrix:
  include:

    - python: "3.10"
      env: TOXENV=py310

    # Linters

    - python: "3.10"
      env: TOXENV=linting

notifications:
  email: false
