dist: bionic
language: python
cache: pip

before_script:
  - pip install tox

script: tox

matrix:
  include:

    - python: "3.10"
      env: TOXENV=py310
      before_script: sudo apt-get update && sudo apt-get install ffmpeg

    # Linters

    - python: "3.10"
      env: TOXENV=linting

notifications:
  email: false
