dist: bionic
language: python
cache: pip

before_script:
  - pip install tox
  - apt-get update && apt-get install ffmpeg

script: tox

matrix:
  include:

    - python: "3.10"
      env: TOXENV=py310

    # Linters

    - python: "3.10"
      env: TOXENV=linting

notifications:
  email: false
