dist: bionic
language: python
cache: pip

before_script:
  - pip install tox
  - if [ ${FFMPEG} = true ]; then sudo apt-get update && sudo apt-get install ffmpeg; fi

script: tox

matrix:
  include:

    - python: "3.10"
      env: 
        - TOXENV=py310
        - FFMPEG=true

    # Linters

    - python: "3.10"
      env: TOXENV=linting

notifications:
  email: false
