language: python
cache: pip
env:
  global:
    - TIMESTAMP: $(date '+%Y%m%d%H%M%S')

before_script:
  - pip install tox
  - if [ ${FFMPEG} = true ]; then sudo apt-get update && sudo apt-get install ffmpeg; fi

script: tox

before_deploy:
  - docker build -t ${DOCKER_REPO} .
  - if [ ! -d deploy_scripts ]; then git clone https://github.com/RockefellerArchiveCenter/deploy_scripts.git; fi
deploy:
  provider: script
  script: bash deploy_scripts/containers/push_image_to_ecr.sh
  on:
    branch: base

notifications:
  email: false
